stages:
  - build
  - testing


build-package:
  image: python:3.12-bookworm
  stage: build
  script:
    - pip3 install build
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl

mypy:
  image: python:3.12-bookworm
  stage: testing
  script:
    - pip3 install mypy
    - pip3 install -r requirements.txt
    - mypy --python-version 3.8  --install-types --ignore-missing-imports --check-untyped-defs --non-interactive ./lib/

pylint:
  image: python:3.12-bookworm
  stage: testing
  script:
    - pip3 install pylint
    - pip3 install -r requirements.txt
    - pylint --disable=F0401 --py-version 3.8 -rn -sn -E ./lib/
    - pylint --disable=F0401 --py-version 3.8 -rn -sn -E ./apps/